name: Test Python Project

on: 
    workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: actions/checkout@v
    - name: Install dependencies
      run: pip install -r requirements.txt


    - name: Run tests
      run: unittest
